// React/Monday10Mar/src/components/BestSelling/BestSelling.jsx
import { useState, useEffect } from "react";
import api from "../../services/api";
import CourseCard from "../CourseCard/CourseCard";
import "./BestSelling.css";

function BestSelling() {
  const [courses, setCourses] = useState([]);

  useEffect(() => {
    api.getCourses().then((data) => {
      console.log("Total courses fetched:", data.length);
      const bestSellers = data.filter((course) => course.bestseller);
      console.log("Bestseller courses:", bestSellers.length);
      setCourses(bestSellers);
    });
  }, []);

  return (
    <div className="container best-selling">
      <h1>Best Selling Courses</h1>
      <div className="course-grid">
        {courses.map((course) => (
          <CourseCard key={course.id} course={course} />
        ))}
      </div>
    </div>
  );
}

export default BestSelling;

// Angular/course-win-spa-ang/src/app/components/best-selling/best-selling.component.ts
import { Component, OnInit } from '@angular/core';
import { CourseService } from '../../services/course.service';
import { Course } from '../../models/course.model';

@Component({
  selector: 'app-best-selling',
  templateUrl: './best-selling.component.html',
  styleUrls: ['./best-selling.component.css'],
})
export class BestSellingComponent implements OnInit {
  courses: Course[] = [];

  constructor(private courseService: CourseService) {}

  ngOnInit() {
    this.courseService.getCourses().subscribe((data) => {
      this.courses = data.filter((course) => course.bestseller);
    });
  }
}

<div class="container">
  <h1>Best Selling Courses</h1>
  <div class="course-grid">
    <app-course-card *ngFor="let course of courses" [course]="course">
    </app-course-card>
  </div>
</div>
