// Angular/course-win-spa-ang/src/app/components/course-list/course-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CourseService } from '../../services/course.service';
import { Course } from '../../models/course.model';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-course-list',
  templateUrl: './course-list.component.html',
  styleUrls: ['./course-list.component.css'],
})
export class CourseListComponent implements OnInit {
  courses: Course[] = [];
  filterForm: FormGroup;
  categories: string[] = ['Game Design', 'Programming', 'Art', 'Sound Design'];

  constructor(private courseService: CourseService, private fb: FormBuilder) {
    this.filterForm = this.fb.group({
      category: [''],
      minPrice: [0],
      maxPrice: [1000],
      searchTerm: [''],
    });
  }

  ngOnInit() {
    this.courseService.getCourses().subscribe((data) => {
      this.courses = data.filter((course) => !course.bestseller); // Exclude bestsellers from explore
    });
  }
}

<div class="container">
  <h1>Welcome to Course-Win</h1>
  <p>
    Unleash your game development potential with industry-leading courses
    designed by experts.
  </p>
  <div class="buttons">
    <a routerLink="/courses" class="btn">Explore Courses</a>
    <a routerLink="/best-selling" class="btn btn-secondary">Best Selling</a>
    <a routerLink="/about-us" class="btn btn-secondary">About Us</a>
    <a routerLink="/plans-pricing" class="btn btn-secondary">Plans & Pricing</a>
    <a routerLink="/feedback" class="btn btn-secondary">Feedback</a>
  </div>
  <hr />

  <h2>Explore Our Courses</h2>

  <form [formGroup]="filterForm">
    <select formControlName="category">
      <option value="">All Categories</option>
      <option *ngFor="let category of categories" [value]="category">
        {{ category }}
      </option>
    </select>
    <input type="number" formControlName="minPrice" placeholder="Min Price" />
    <input type="number" formControlName="maxPrice" placeholder="Max Price" />
    <input
      type="text"
      formControlName="searchTerm"
      placeholder="Search courses..."
    />
  </form>

  <div class="course-grid">
    <app-course-card
      *ngFor="let course of courses | filterCourse : filterForm.value"
      [course]="course"
    >
    </app-course-card>
  </div>
</div>

// React/Monday10Mar/src/components/CourseList/CourseList.jsx
import { useState, useEffect } from "react";
import api from "../../services/api";
import CourseCard from "../CourseCard/CourseCard";
import "./CourseList.css";

function CourseList() {
  const [courses, setCourses] = useState([]);
  const [filter, setFilter] = useState({
    category: "",
    minPrice: 0,
    maxPrice: 1000,
    searchTerm: "",
  });

  useEffect(() => {
    api.getCourses().then((data) => {
      console.log("Total courses fetched:", data.length);
      const nonBestSellers = data.filter((course) => !course.bestseller);
      console.log("Non-bestseller courses:", nonBestSellers.length);
      setCourses(nonBestSellers);
    });
  }, []);

  const categories = ["Game Design", "Programming", "Art", "Sound Design"];

  const handleFilterChange = (e) => {
    setFilter({ ...filter, [e.target.name]: e.target.value });
  };

  const filteredCourses = courses.filter((course) => {
    const matchesCategory = filter.category
      ? course.category === filter.category
      : true;
    const matchesPrice =
      course.price >= filter.minPrice && course.price <= filter.maxPrice;
    const matchesSearch = filter.searchTerm
      ? course.title.toLowerCase().includes(filter.searchTerm.toLowerCase()) ||
        course.description
          .toLowerCase()
          .includes(filter.searchTerm.toLowerCase())
      : true;
    return matchesCategory && matchesPrice && matchesSearch;
  });

  return (
    <div className="container course-list">
      <h1>Welcome to Course-Win</h1>
      <p>
        Unleash your game development potential with industry-leading courses
        designed by experts.
      </p>
      <hr className="divider" />
      <h2>Explore Our Courses</h2>
      <form className="filter-form">
        <select
          name="category"
          value={filter.category}
          onChange={handleFilterChange}
        >
          <option value="">All Categories</option>
          {categories.map((category) => (
            <option key={category} value={category}>
              {category}
            </option>
          ))}
        </select>
        <input
          type="number"
          name="minPrice"
          value={filter.minPrice}
          onChange={handleFilterChange}
          placeholder="Min Price"
        />
        <input
          type="number"
          name="maxPrice"
          value={filter.maxPrice}
          onChange={handleFilterChange}
          placeholder="Max Price"
        />
        <input
          type="text"
          name="searchTerm"
          value={filter.searchTerm}
          onChange={handleFilterChange}
          placeholder="Search courses..."
        />
      </form>
      <div className="course-grid">
        {filteredCourses.map((course) => (
          <CourseCard key={course.id} course={course} />
        ))}
      </div>
    </div>
  );
}

export default CourseList;
