// Angular/course-win-spa-ang/src/app/components/course-card/course-card.component.ts
import { Component, Input } from '@angular/core';
import { Course } from '../../models/course.model';

@Component({
  selector: 'app-course-card',
  templateUrl: './course-card.component.html',
  styleUrls: ['./course-card.component.css'],
})
export class CourseCardComponent {
  @Input() course!: Course;
}

<div class="card">
  <h3>{{ course.title }}</h3>
  <p>{{ course.description }}</p>
  <p><strong>Category:</strong> {{ course.category }}</p>
  <p><strong>Price:</strong> ${{ course.price }}</p>
  <p><strong>Rating:</strong> {{ course.rating }}/5</p>
  <p><strong>Duration:</strong> {{ course.duration }}</p>
  <p><strong>Instructor:</strong> {{ course.instructor }}</p>
  <button class="enroll-btn">Enroll Now</button>
</div>

// React/Monday10Mar/src/components/CourseCard/CourseCard.jsx
import "./CourseCard.css";

function CourseCard({ course }) {
  return (
    <div className="card">
      <h3>{course.title}</h3>
      <p>{course.description}</p>
      <p>
        <strong>Category:</strong> {course.category}
      </p>
      <p>
        <strong>Price:</strong> ${course.price}
      </p>
      <p>
        <strong>Rating:</strong> {course.rating}/5
      </p>
      <p>
        <strong>Duration:</strong> {course.duration}
      </p>
      <p>
        <strong>Instructor:</strong> {course.instructor}
      </p>
      <button className="enroll-btn">Enroll Now</button>
    </div>
  );
}

export default CourseCard;
